FROM nginx:latest

WORKDIR /etc/nginx/

RUN mkdir /etc/nginx/sites-available && mkdir /etc/nginx/sites-enabled

COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./config/sites-available /etc/nginx/sites-available

RUN cd sites-enabled && ln -s /etc/nginx/sites-available/pydjango

EXPOSE 80 443

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]