version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./bazarr/config:/config
      - ./movies:/movies #optional
      - ./tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

