version: "3.3"

services:
  
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes: 
      - ./data:/var/lib/mysql
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: "no"
    ports:
      - 8080:8080
    depends_on: 
      - mysql